In [70]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [71]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train.head()

,id,emotional_charge_2,groove_efficiency_1,beat_frequency_1,organic_texture_2,composition_label_0,harmonic_scale_1,intensity_index_0,duration_ms_0,album_name_length,...,time_signature_0,duration_ms_1,harmonic_scale_0,time_signature_2,rhythmic_cohesion_2,emotional_resonance_0,harmonic_scale_2,intensity_index_2,instrumental_density_0,target
0,76339,0.482850,1.169231,80.018,0.0201,Country Stuff (feat. Jake Owen),1.0,0.789,154586.0,NaN,...,4.0,161853.0,7.0,4.0,NaN,0.607,7.0,0.7250,0.000000,74
1,80006,0.267862,1.321321,147.966,0.3340,Solitude,6.0,0.715,46874.0,15.0,...,4.0,155619.0,1.0,4.0,0.843,0.783,4.0,NaN,0.043200,2
2,83501,0.242606,1.285319,142.980,0.1110,BDFFRNT (Saved from Conformity),4.0,NaN,264665.0,7.0,...,4.0,209378.0,6.0,4.0,NaN,0.211,10.0,0.6020,0.000000,35
3,81530,0.426400,1.279435,123.063,0.1960,Headlights (feat. Ilsey),5.0,0.685,209208.0,5.0,...,4.0,219043.0,11.0,4.0,0.702,0.369,NaN,0.8200,0.000335,70
4,60534,0.000000,0.974906,132.722,0.0811,Afraid,6.0,0.856,215346.0,5.0,...,4.0,258893.0,1.0,0.0,0.000,0.631,1.0,0.0221,0.000000,78

In [72]:
test.head()
test_ids = test["id"]

In [73]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 61609 entries, 0 to 61608
Data columns (total 62 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          61609 non-null  int64
 1   emotional_charge_2          59167 non-null  float64
 2   groove_efficiency_1         61429 non-null  float64
 3   beat_frequency_1            61223 non-null  float64
 4   organic_texture_2           61226 non-null  float64
 5   composition_label_0         58660 non-null  str
 6   harmonic_scale_1            58304 non-null  float64
 7   intensity_index_0           55638 non-null  float64
 8   duration_ms_0               60320 non-null  float64
 9   album_name_length           52015 non-null  float64
 10  beat_frequency_0            51878 non-null  float64
 11  beat_frequency_2            59843 non-null  float64
 12  artist_count                58348 non-null  float64
 13  composition_label_1         60149 non-null  str
 14  publication_timestamp       60101 non-null  str
 15  weekday_of_release          56551 non-null  str
 16  album_component_count       57246 non-null  float64
 17  emotional_charge_1          57595 non-null  float64
 18  emotional_charge_0          55505 non-null  float64
 19  tonal_mode_2                59800 non-null  float64
 20  key_variety                 56204 non-null  float64
 21  performance_authenticity_2  59695 non-null  float64
 22  performance_authenticity_0  59504 non-null  float64
 23  season_of_release           61136 non-null  str
 24  time_signature_1            59746 non-null  float64
 25  duration_ms_2               60481 non-null  float64
 26  lunar_phase                 60608 non-null  str
 27  instrumental_density_2      57455 non-null  float64
 28  organic_texture_0           57272 non-null  float64
 29  creator_collective          52695 non-null  str
 30  vocal_presence_2            59075 non-null  float64
 31  tonal_mode_1                57211 non-null  float64
 32  vocal_presence_1            60744 non-null  float64
 33  vocal_presence_0            61499 non-null  float64
 34  intensity_index_1           59491 non-null  float64
 35  organic_immersion_0         57766 non-null  float64
 36  tonal_mode_0                61328 non-null  float64
 37  groove_efficiency_2         55863 non-null  float64
 38  instrumental_density_1      54132 non-null  float64
 39  organic_immersion_2         55974 non-null  float64
 40  duration_consistency        58532 non-null  float64
 41  composition_label_2         57146 non-null  str
 42  organic_texture_1           59481 non-null  float64
 43  rhythmic_cohesion_0         54426 non-null  float64
 44  track_identifier            57173 non-null  str
 45  emotional_resonance_1       59642 non-null  float64
 46  rhythmic_cohesion_1         60610 non-null  float64
 47  performance_authenticity_1  57924 non-null  float64
 48  tempo_volatility            51192 non-null  float64
 49  organic_immersion_1         61471 non-null  float64
 50  groove_efficiency_0         60133 non-null  float64
 51  emotional_resonance_2       56733 non-null  float64
 52  time_signature_0            59704 non-null  float64
 53  duration_ms_1               52504 non-null  float64
 54  harmonic_scale_0            53925 non-null  float64
 55  time_signature_2            58455 non-null  float64
 56  rhythmic_cohesion_2         56049 non-null  float64
 57  emotional_resonance_0       60063 non-null  float64
 58  harmonic_scale_2            57142 non-null  float64
 59  intensity_index_2           60916 non-null  float64
 60  instrumental_density_0      60900 non-null  float64
 61  target                      61609 non-null  int64
dtypes: float64(51), int64(2), str(9)
memory usage: 29.1 MB

In [74]:
train.describe()

,id,emotional_charge_2,groove_efficiency_1,beat_frequency_1,organic_texture_2,harmonic_scale_1,intensity_index_0,duration_ms_0,album_name_length,beat_frequency_0,...,time_signature_0,duration_ms_1,harmonic_scale_0,time_signature_2,rhythmic_cohesion_2,emotional_resonance_0,harmonic_scale_2,intensity_index_2,instrumental_density_0,target
count,61609.000000,59167.000000,61429.000000,61223.000000,61226.000000,58304.000000,55638.000000,6.032000e+04,52015.000000,51878.000000,...,59704.000000,5.250400e+04,53925.000000,58455.000000,56049.000000,60063.000000,57142.000000,60916.000000,60900.000000,61609.000000
mean,51390.780162,0.316976,1.238856,121.022910,0.274748,5.192594,0.604426,2.011315e+05,18.225723,119.133973,...,3.874849,2.110477e+05,5.212499,3.901274,0.612252,0.458851,5.288894,0.616045,0.148391,52.067328
std,29659.344472,0.212777,6.171617,30.467061,0.303020,3.629153,0.243943,1.100738e+05,14.404713,32.067971,...,0.564558,8.911099e+04,3.571288,0.465295,0.179591,0.261196,3.567118,0.230109,0.306915,21.569248
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.485000e+03,1.000000,0.000000,...,0.000000,4.120000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,25832.000000,0.143877,0.730914,96.138000,0.027125,2.000000,0.447000,1.482340e+05,9.000000,94.802250,...,4.000000,1.682000e+05,2.000000,4.000000,0.506000,0.243000,2.000000,0.477000,0.000000,37.000000
50%,51410.000000,0.291060,1.004894,120.012000,0.141000,5.000000,0.633000,1.959215e+05,14.000000,119.893000,...,4.000000,2.029730e+05,5.000000,4.000000,0.630000,0.449000,5.000000,0.646000,0.000019,57.000000
75%,77069.000000,0.466860,1.358251,141.401000,0.454000,8.000000,0.803000,2.402488e+05,23.000000,140.023000,...,4.000000,2.413605e+05,8.000000,4.000000,0.745000,0.663000,8.000000,0.791000,0.024600,69.000000
max,102681.000000,0.976063,654.000000,239.983000,0.996000,11.000000,1.000000,3.664274e+06,199.000000,235.998000,...,5.000000,3.550973e+06,11.000000,5.000000,0.979000,1.000000,11.000000,1.000000,1.000000,100.000000

In [75]:
train.dtypes.unique()

array([dtype('int64'), dtype('float64'),
       <StringDtype(storage='python', na_value=nan)>], dtype=object)

In [76]:
cat_cols = train.select_dtypes(include=["str" ]).columns
num_cols = train.select_dtypes(include=["int64", "float64"]).columns

unique_counts = train[cat_cols].nunique().sort_values(ascending=False)
print(unique_counts.head(10))

track_identifier         22991
composition_label_1      22930
composition_label_2      22169
composition_label_0      21709
creator_collective       15139
publication_timestamp     6061
weekday_of_release           7
season_of_release            4
lunar_phase                  4
dtype: int64

In [77]:
for df in [train, test]:
    df["publication_timestamp"] = pd.to_datetime(df["publication_timestamp"], errors="coerce")
    df["pub_year"] = df["publication_timestamp"].dt.year
    df["pub_month"] = df["publication_timestamp"].dt.month
    df["pub_day"] = df["publication_timestamp"].dt.day
    df["pub_dayofweek"] = df["publication_timestamp"].dt.dayofweek

train.drop(columns=["publication_timestamp"], inplace=True)
test.drop(columns=["publication_timestamp"], inplace=True)

In [78]:
y = train["target"]
X = train.drop(columns=["target"])
X_test = test.copy()

In [79]:
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size=0.2, random_state=42)

In [80]:
drop_cols = ["id", "track_identifier"]

X_train = X_train.drop(columns=drop_cols)
X_val = X_val.drop(columns=drop_cols)
X_test_model = X_test.drop(columns=drop_cols)

In [81]:
high_card_cols = [
    "composition_label_0",
    "composition_label_1",
    "composition_label_2",
    "creator_collective"
]

for col in high_card_cols:
    freq = X_train[col].value_counts(normalize=True)
    X_train[col] = X_train[col].map(freq)
    X_val[col] = X_val[col].map(freq).fillna(0)
    X_test_model[col] = X_test_model[col].map(freq).fillna(0)

In [82]:
num_cols = X_train.select_dtypes(["int64", "float64"]).columns
cat_cols = X_train.select_dtypes(["str","object"]).columns


corrs = X_train[num_cols].corr()
print(corrs)

                            emotional_charge_2  groove_efficiency_1  \
emotional_charge_2                    1.000000             0.006038
groove_efficiency_1                   0.006038             1.000000
beat_frequency_1                      0.082079            -0.047250
organic_texture_2                    -0.370537            -0.018761
composition_label_0                   0.006143            -0.000923
harmonic_scale_1                      0.010940             0.000697
intensity_index_0                     0.401164             0.036206
duration_ms_0                        -0.011000            -0.012154
album_name_length                    -0.070925             0.033707
beat_frequency_0                      0.101669            -0.009692
beat_frequency_2                      0.140592             0.000555
artist_count                         -0.117246             0.012858
composition_label_1                  -0.021132            -0.015788
album_component_count                -0.060852             0.010768
emotional_charge_1                    0.500207            -0.000643
emotional_charge_0                    0.474444             0.006751
tonal_mode_2                         -0.007200             0.006236
key_variety                           0.025852             0.006912
performance_authenticity_2            0.073312             0.029699
performance_authenticity_0            0.039570             0.019828
time_signature_1                      0.073061            -0.143523
duration_ms_2                        -0.004196             0.000888
instrumental_density_2               -0.310736             0.003575
organic_texture_0                    -0.264085            -0.032669
creator_collective                   -0.002841             0.005269
vocal_presence_2                      0.008183            -0.008362
tonal_mode_1                         -0.008564            -0.008584
vocal_presence_1                      0.005425            -0.023124
vocal_presence_0                      0.016217            -0.007687
intensity_index_1                     0.424296             0.057949
organic_immersion_0                  -0.218988            -0.027555
tonal_mode_0                          0.008000             0.010036
groove_efficiency_2                  -0.036610             0.003035
instrumental_density_1               -0.297701             0.020051
organic_immersion_2                  -0.279330            -0.016944
duration_consistency                 -0.076532             0.009873
composition_label_2                  -0.021937            -0.015713
organic_texture_1                    -0.290810            -0.024055
rhythmic_cohesion_0                   0.205600            -0.044637
emotional_resonance_1                 0.415643            -0.037998
rhythmic_cohesion_1                   0.190687            -0.119017
performance_authenticity_1            0.020311             0.034578
tempo_volatility                     -0.055682             0.052130
organic_immersion_1                  -0.220884            -0.031883
groove_efficiency_0                  -0.005221             0.002623
emotional_resonance_2                 0.877323            -0.014960
time_signature_0                      0.072528            -0.024962
duration_ms_1                         0.011766            -0.019832
harmonic_scale_0                     -0.003175             0.003654
time_signature_2                      0.114954            -0.007344
rhythmic_cohesion_2                   0.307578            -0.051410
emotional_resonance_0                 0.391256            -0.013388
harmonic_scale_2                      0.041930             0.001819
intensity_index_2                     0.673629             0.035970
instrumental_density_0               -0.272749             0.007216
pub_year                             -0.138534            -0.014659
pub_month                            -0.049540            -0.007077
pub_day                              -0.030072            -0.001221
pub_dayofweek                        -0.061049            -0.018291

                            beat_frequency_1  organic_texture_2  \
emotional_charge_2                  0.082079          -0.370537
groove_efficiency_1                -0.047250          -0.018761
beat_frequency_1                    1.000000          -0.123528
organic_texture_2                  -0.123528           1.000000
composition_label_0                -0.014773          -0.056650
harmonic_scale_1                    0.011814          -0.010054
intensity_index_0                   0.133569          -0.469024
duration_ms_0                      -0.003586           0.036900
album_name_length                  -0.039565           0.160042
beat_frequency_0                    0.137704          -0.139235
beat_frequency_2                    0.111546          -0.162899
artist_count                       -0.063497           0.156029
composition_label_1                 0.022460          -0.099428
album_component_count              -0.038901           0.097698
emotional_charge_1                  0.120171          -0.310461
emotional_charge_0                  0.105252          -0.243631
tonal_mode_2                        0.006501           0.023729
key_variety                         0.017416          -0.025382
performance_authenticity_2          0.008989          -0.059095
performance_authenticity_0         -0.002580          -0.078813
time_signature_1                    0.047493          -0.148896
duration_ms_2                      -0.020950          -0.042020
instrumental_density_2             -0.088543           0.299138
organic_texture_0                  -0.101032           0.574870
creator_collective                  0.001394           0.023615
vocal_presence_2                    0.003585          -0.051012
tonal_mode_1                       -0.000997           0.021305
vocal_presence_1                    0.063142          -0.091770
vocal_presence_0                   -0.009952          -0.089364
intensity_index_1                   0.169889          -0.547067
organic_immersion_0                -0.087410           0.461306
tonal_mode_0                        0.000430           0.052808
groove_efficiency_2                 0.008498           0.017838
instrumental_density_1             -0.083607           0.290766
organic_immersion_2                -0.106125           0.719564
duration_consistency               -0.041900           0.113097
composition_label_2                 0.026450          -0.097791
organic_texture_1                  -0.142092           0.655136
rhythmic_cohesion_0                 0.077170          -0.175521
emotional_resonance_1               0.087008          -0.151184
rhythmic_cohesion_1                 0.008083          -0.213970
performance_authenticity_1         -0.032848          -0.079419
tempo_volatility                    0.126450           0.067242
organic_immersion_1                -0.109358           0.489375
groove_efficiency_0                -0.012542           0.004650
emotional_resonance_2               0.048697          -0.169889
time_signature_0                    0.083010          -0.101034
duration_ms_1                      -0.015364           0.009335
harmonic_scale_0                   -0.003854          -0.015810
time_signature_2                    0.065495          -0.170508
rhythmic_cohesion_2                 0.076329          -0.253467
emotional_resonance_0               0.081172          -0.096705
harmonic_scale_2                   -0.008493          -0.002177
intensity_index_2                   0.130111          -0.656767
instrumental_density_0             -0.095357           0.255476
pub_year                            0.009844           0.000522
pub_month                          -0.019095           0.009056
pub_day                             0.003570          -0.025456
pub_dayofweek                       0.019793           0.004568

                            composition_label_0  harmonic_scale_1  \
emotional_charge_2                     0.006143          0.010940
groove_efficiency_1                   -0.000923          0.000697
beat_frequency_1                      -0.014773          0.011814
organic_texture_2                     -0.056650         -0.010054
composition_label_0                    1.000000         -0.000766
harmonic_scale_1                      -0.000766          1.000000
intensity_index_0                     -0.070779          0.016080
duration_ms_0                         -0.163766         -0.006451
album_name_length                     -0.010461         -0.010972
beat_frequency_0                      -0.067098         -0.002545
beat_frequency_2                      -0.018085          0.001323
artist_count                          -0.003891          0.000584
composition_label_1                    0.064694         -0.036253
album_component_count                  0.010790          0.030824
emotional_charge_1                    -0.007096          0.055990
emotional_charge_0                    -0.068725          0.028092
tonal_mode_2                          -0.025043         -0.034969
key_variety                            0.004545          0.059731
performance_authenticity_2             0.027887         -0.000874
performance_authenticity_0             0.071620          0.008633
time_signature_1                       0.015530         -0.006292
duration_ms_2                         -0.019128          0.008539
instrumental_density_2                -0.054676          0.008631
organic_texture_0                      0.055559         -0.020822
creator_collective                    -0.025424         -0.005320
vocal_presence_2                       0.100824          0.009011
tonal_mode_1                          -0.027819         -0.201288
vocal_presence_1                       0.096273          0.030144
vocal_presence_0                       0.110580          0.001086
intensity_index_1                      0.034218          0.044667
organic_immersion_0                   -0.046423         -0.029294
tonal_mode_0                          -0.029961          0.005798
groove_efficiency_2                   -0.000163          0.005878
instrumental_density_1                -0.052224         -0.006762
organic_immersion_2                   -0.050425         -0.006782
duration_consistency                   0.088562          0.011280
composition_label_2                    0.056899         -0.051147
organic_texture_1                     -0.057774         -0.006196
rhythmic_cohesion_0                   -0.013400         -0.005405
emotional_resonance_1                 -0.015615          0.052211
rhythmic_cohesion_1                    0.085341          0.022329
performance_authenticity_1             0.015254          0.004126
tempo_volatility                       0.014852          0.016281
organic_immersion_1                   -0.043447          0.006199
groove_efficiency_0                    0.047041         -0.000551
emotional_resonance_2                  0.000496          0.000462
time_signature_0                      -0.041485         -0.015380
duration_ms_1                         -0.014743          0.018016
harmonic_scale_0                       0.000130          0.033359
time_signature_2                       0.021930          0.012489
rhythmic_cohesion_2                    0.072662         -0.000990
emotional_resonance_0                 -0.027991          0.023934
harmonic_scale_2                      -0.009330          0.009565
intensity_index_2                      0.033437          0.012547
instrumental_density_0                -0.006396          0.004484
pub_year                               0.015060         -0.005095
pub_month                              0.012074         -0.006636
pub_day                                0.001615         -0.019750
pub_dayofweek                         -0.010560          0.008969

                            intensity_index_0  duration_ms_0  \
emotional_charge_2                   0.401164      -0.011000
groove_efficiency_1                  0.036206      -0.012154
beat_frequency_1                     0.133569      -0.003586
organic_texture_2                   -0.469024       0.036900
composition_label_0                 -0.070779      -0.163766
harmonic_scale_1                     0.016080      -0.006451
intensity_index_0                    1.000000       0.115419
duration_ms_0                        0.115419       1.000000
album_name_length                   -0.086079       0.064116
beat_frequency_0                     0.213298       0.071659
beat_frequency_2                     0.141860      -0.002052
artist_count                        -0.143102       0.104748
composition_label_1                  0.038296      -0.065837
album_component_count               -0.099422      -0.105388
emotional_charge_1                   0.434924      -0.019707
emotional_charge_0                   0.672995       0.057550
tonal_mode_2                         0.008403       0.009732
key_variety                          0.025203      -0.016130
performance_authenticity_2           0.097918       0.008500
performance_authenticity_0           0.161386      -0.067878
time_signature_1                     0.119165       0.021208
duration_ms_2                        0.047327       0.509656
instrumental_density_2              -0.278067       0.041787
organic_texture_0                   -0.645739      -0.083231
creator_collective                   0.020466       0.020744
vocal_presence_2                    -0.037961      -0.126484
tonal_mode_1                        -0.017962       0.019933
vocal_presence_1                    -0.017548      -0.109918
vocal_presence_0                    -0.006125      -0.178730
intensity_index_1                    0.641168      -0.027551
organic_immersion_0                 -0.423951       0.568147
tonal_mode_0                        -0.034336      -0.008661
groove_efficiency_2                 -0.003937      -0.018700
instrumental_density_1              -0.280194       0.051136
organic_immersion_2                 -0.339323       0.336334
duration_consistency                -0.169418       0.311418
composition_label_2                  0.038285      -0.062747
organic_texture_1                   -0.479937       0.047052
rhythmic_cohesion_0                  0.166859      -0.043914
emotional_resonance_1                0.238038      -0.041552
rhythmic_cohesion_1                  0.086357      -0.125838
performance_authenticity_1           0.117133      -0.006404
tempo_volatility                    -0.087087      -0.073488
organic_immersion_1                 -0.340720       0.331176
groove_efficiency_0                 -0.009545      -0.094196
emotional_resonance_2                0.220149      -0.037046
time_signature_0                     0.165724       0.097529
duration_ms_1                        0.047878       0.542795
harmonic_scale_0                     0.049301       0.002696
time_signature_2                     0.097354       0.002764
rhythmic_cohesion_2                  0.073876      -0.124842
emotional_resonance_0                0.342306      -0.025905
harmonic_scale_2                     0.013001       0.003725
intensity_index_2                    0.612763      -0.007814
instrumental_density_0              -0.314119      -0.013872
pub_year                            -0.077919      -0.155920
pub_month                           -0.023627      -0.028910
pub_day                             -0.008157      -0.048256
pub_dayofweek                       -0.053982      -0.034001

                            album_name_length  beat_frequency_0  ...  \
emotional_charge_2                  -0.070925          0.101669  ...
groove_efficiency_1                  0.033707         -0.009692  ...
beat_frequency_1                    -0.039565          0.137704  ...
organic_texture_2                    0.160042         -0.139235  ...
composition_label_0                 -0.010461         -0.067098  ...
harmonic_scale_1                    -0.010972         -0.002545  ...
intensity_index_0                   -0.086079          0.213298  ...
duration_ms_0                        0.064116          0.071659  ...
album_name_length                    1.000000         -0.052076  ...
beat_frequency_0                    -0.052076          1.000000  ...
beat_frequency_2                    -0.029112          0.131272  ...
artist_count                         0.128347         -0.051907  ...
composition_label_1                 -0.012483         -0.026072  ...
album_component_count                0.199002          0.019880  ...
emotional_charge_1                  -0.064382          0.119387  ...
emotional_charge_0                  -0.040553          0.175427  ...
tonal_mode_2                         0.033049         -0.020857  ...
key_variety                         -0.060599         -0.013574  ...
performance_authenticity_2           0.030456          0.002394  ...
performance_authenticity_0           0.015107         -0.017137  ...
time_signature_1                    -0.087747          0.091663  ...
duration_ms_2                        0.025403          0.002005  ...
instrumental_density_2               0.114865         -0.092651  ...
organic_texture_0                    0.120257         -0.204189  ...
creator_collective                   0.224965         -0.005503  ...
vocal_presence_2                    -0.006366         -0.009888  ...
tonal_mode_1                         0.046819          0.009879  ...
vocal_presence_1                    -0.017195         -0.008700  ...
vocal_presence_0                    -0.009582          0.016693  ...
intensity_index_1                   -0.139289          0.135959  ...
organic_immersion_0                  0.141509         -0.114272  ...
tonal_mode_0                         0.052187         -0.014086  ...
groove_efficiency_2                  0.011619         -0.018269  ...
instrumental_density_1               0.101457         -0.085233  ...
organic_immersion_2                  0.147187         -0.107328  ...
duration_consistency                 0.106602         -0.092510  ...
composition_label_2                 -0.010358         -0.031696  ...
organic_texture_1                    0.163303         -0.115247  ...
rhythmic_cohesion_0                 -0.136478          0.089232  ...
emotional_resonance_1               -0.033712          0.093871  ...
rhythmic_cohesion_1                 -0.157067          0.069583  ...
performance_authenticity_1           0.029988         -0.026072  ...
tempo_volatility                     0.004577          0.036496  ...
organic_immersion_1                  0.148541         -0.083931  ...
groove_efficiency_0                  0.024010         -0.205016  ...
emotional_resonance_2               -0.047542          0.080733  ...
time_signature_0                    -0.039358          0.185177  ...
duration_ms_1                        0.031055         -0.003819  ...
harmonic_scale_0                    -0.000531          0.029672  ...
time_signature_2                    -0.048776          0.045156  ...
rhythmic_cohesion_2                 -0.157607          0.081591  ...
emotional_resonance_0               -0.025735          0.147669  ...
harmonic_scale_2                    -0.017723          0.002535  ...
intensity_index_2                   -0.132264          0.129427  ...
instrumental_density_0               0.085129         -0.112073  ...
pub_year                            -0.102073         -0.003010  ...
pub_month                            0.035019         -0.008834  ...
pub_day                             -0.045203          0.022397  ...
pub_dayofweek                       -0.070689         -0.007560  ...

                            time_signature_2  rhythmic_cohesion_2  \
emotional_charge_2                  0.114954             0.307578
groove_efficiency_1                -0.007344            -0.051410
beat_frequency_1                    0.065495             0.076329

In [83]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy = "median")),
    
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ("num",num_pipeline, num_cols ),
    ("cat", cat_pipeline, cat_cols)
])

In [84]:
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=1.0),
    "RandomForest": RandomForestRegressor(
        n_estimators=80,
        max_depth=15,
        min_samples_split=10,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1
    ),
    "ExtraTrees": ExtraTreesRegressor(
        n_estimators=80,
        max_depth=15,
        min_samples_split=10,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1
    ),
    "DecisionTree": DecisionTreeRegressor(
        max_depth=15,
        min_samples_split=10,
        min_samples_leaf=5,
        random_state=42
    ),
    "Gradient Boost": GradientBoostingRegressor(
        n_estimators=100,
        learning_rate=0.05,
        max_depth=5,
        random_state=42
    ),
    "Ada Boost": AdaBoostRegressor(
        n_estimators=100,
        learning_rate=0.05,
        random_state=42
    )
}

In [85]:
results = []
trained_models = {}

for name, regressor in models.items():
    model = Pipeline([
        ("preprocessor", preprocessor),
        ("regressor", regressor) 
    ])

    model.fit(X_train,y_train)
    val_preds = model.predict(X_val)
    
    
    # Model evaluation
    mse = mean_squared_error(y_val, val_preds)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_val, val_preds)
    r2 = r2_score(y_val, val_preds)


    results.append(
        {
            "Model": name,
            "MSE": mse,
            "RMSE": rmse,
            "MAE": mae,
            "R^2": r2
        }
    )

    trained_models[name] = model

results_df = pd.DataFrame(results).sort_values("RMSE")
print(results_df)

              Model         MSE       RMSE        MAE       R^2
2      RandomForest  153.359330  12.383833   8.865956  0.670724
3        ExtraTrees  159.929676  12.646331   9.038451  0.656616
5    Gradient Boost  170.868857  13.071681  10.245894  0.633129
6         Ada Boost  224.190008  14.972976  11.951465  0.518644
0  LinearRegression  247.886376  15.744408  12.663604  0.467765
4      DecisionTree  251.801582  15.868257  10.574671  0.459359
1             Ridge  374.072414  19.340952  15.608958  0.196832

In [86]:
best_model_name = results_df.iloc[0]["Model"]
best_model = trained_models[best_model_name]

test_preds = best_model.predict(X_test_model)

In [87]:
submission = pd.DataFrame({
    "id": test_ids,
    "target": test_preds
})

submission.to_csv("submission.csv", index=False)